-- Chat ordering and inbox activity depend on receiving authoritative inserts
-- generated by Postgres while the relevant screen is open.
do $$
begin
  alter publication supabase_realtime add table public.trip_messages;
exception
  when duplicate_object then null;
end
$$;
